const Routes = {
  SPLASH: 'Splash',
  LOGIN: 'Login',
  SIGN_UP: 'SignUp',
  OTP_VERIFICATION: 'OtpVerification',
  HOME_PAGE: 'HomePage',
  BUTTOM_TAB_BAR: 'BottomTabbar',
  RESET_PASSWORD: 'ResetPassword',
  CHECK_EMAIL: 'CheckEmail',
  CREATE_PASSWORD: 'CreateNewPass',
  ADD_NEW_FAMILY_MEMBERS: 'AddNewFamilyMembers',
  New_Member_Details: 'CreateNewMember',
  VISITOR_MANAGEMENT: 'VisitorManagement',
  VISITOR_LIST: 'VisitorList',
  GATE_PASS_DETAIL: 'GatePassDetails',
  Visitor_Management: 'Visitor Management',
  PANIC_ALARAM_SCREEN: 'PanicAlaramSubDashBoard',
  RENT_PAYMENT_SCREEN: 'RentPaymentScreen',
  UTILITY_BILL_PAYMENT: 'UtilityBillPayment',
  ELECTRICITY_SERVICE_PROVIDER: 'Electricity Service Provider',
  PANIC_ALARAM_SCREEN: 'PanicAlaramSubDashBoard',
  RENT_PAYMENT_SCREEN: 'RentPaymentScreen',
  SOCIETY_PAYMENT_SCREEN: 'SocietyPaymentScreen',
  BILL_REFERNCE_N0: 'Bill Reference No',
  REVIEW_BILL_PAYMENT: 'Review  bill payment',
  TERMS_AND_CONDITIONS: 'Terms & Conditions',
  EDIT_PROFILE: 'editProfile',
};

export default Routes;
